### PR TITLE
added TRENDnet TUC-ET2G support

### PR DESCRIPTION
**Pull request by i-am-at0m**
pulled in changes to support this hardware from a similar driver for Synology: https://github.com/bb-qq/r8152/blob/9015a72f773d8af17261a150ca38627bc9ab1350/r8152.c

### CODE REVIEW

**Comment by jayofdoom** [comment]
Thanks @i-am-at0m for the patch.

@wget I'm likely going to pull this patch in for Gentoo; can we merge it into the repo so it stays in sync?

I'm happy to take a maintainer privs on this repo to help manage PRs/Issues if you'd like.

**Comment by i-am-at0m** [comment]
When researching this, I did find quite a few other IDs that could/should be included, but I wasn't sure what other effects that may have, so I didn't include those. If you look at the file in my linked comment you can see it has quite a few more manufacturers and device IDs than the file in this repo.

**Comment by jayofdoom** [comment]
Yeah but in this case I'm assuming you
1) have this hardware and 
2) are running this patch

Which makes me more apt to trust it and carry the patch... my assumptions are true, right?

**Comment by i-am-at0m** [comment]
I definitely have the hardware.

I'm a little unsure how I'd be able to run it, since I'd have to build this, and then an unRAID plugin, and then figure out how to sideload it. But this one change was used in that other repo to address my specific issue (the ID changing when they rev'd the hardware but didn't change the chipset itself), and matches what I'm getting from lsusb so yeah.

**Comment by jayofdoom** [comment]
Yeah, I'd assume the diff from their repo is mostly hardware IDs, updates like yours.

**Comment by jayofdoom** [comment]
So to be explicit: @i-am-at0m, you have not tested the compiled-module you get from master of this repo + the provided patch on your hardware?

**Comment by hcartiaux** [comment]
I'd say we should close this PR since this device id is now included in 2.17.1.

Indeed, I see quite a few additional device IDs in the linked repository but I have no way to test.

Do not hesitate to reopen the discussion as an issue if needed.

**Pull request closed without merging**
