### PR TITLE
add compat for 6.9.X kernels

### PR DESCRIPTION
**Pull request by hoefling**
My first patch, so please be gentle. Tested with the ethernet expansion card of my framework 13 laptop.

### CODE REVIEW

**Comment by jayofdoom** [comment]
Thanks for the patch, I'm pulling this into the downstream gentoo package.

**Comment by hoefling** [comment]
@jayofdoom hey, this is awesome, I actually did this for patching `net-misc/r8152` on my Gentoo installation as well 👍 hopefully the ebuild patch lands soon in https://bugs.gentoo.org/934074 and I can get rid of my local patches again.

**Comment by jayofdoom** [comment]
@hoefling if you know any gentoo devs, have them merge https://github.com/gentoo/gentoo/pull/37125 :)

**Comment by hcartiaux** [comment]
Thanks for this PR, I'm reviewing the new upstream version 2.18.1 at the moment, I will import it and review your PR after.

**Pull request merged**
